#!/bin/sh
if [ -f .env ]; then
  export $(echo $(cat .env | sed 's/#.*//g'| xargs) | envsubst)
fi

echo files downloading...
curl --location --request POST "https://eu-central-1.aws.data.mongodb-api.com/app/data-fnqrm/endpoint/data/v1/action/find" --header "Content-Type: application/json" --header "Access-Control-Request-Headers: *" --header "api-key: $MONGODB_API" --data-raw '{"collection":"files", "database":"test", "dataSource":"Cluster0"}' > files.json
echo locations downloading...
curl --location --request POST "https://eu-central-1.aws.data.mongodb-api.com/app/data-fnqrm/endpoint/data/v1/action/find" --header "Content-Type: application/json" --header "Access-Control-Request-Headers: *" --header "api-key: $MONGODB_API" --data-raw '{"collection":"locations", "database":"test", "dataSource":"Cluster0"}' > locations.json
echo offers downloading...
curl --location --request POST "https://eu-central-1.aws.data.mongodb-api.com/app/data-fnqrm/endpoint/data/v1/action/find" --header "Content-Type: application/json" --header "Access-Control-Request-Headers: *" --header "api-key: $MONGODB_API" --data-raw '{"collection":"offers", "database":"test", "dataSource":"Cluster0"}' > offers.json
echo relations downloading...
curl --location --request POST "https://eu-central-1.aws.data.mongodb-api.com/app/data-fnqrm/endpoint/data/v1/action/find" --header "Content-Type: application/json" --header "Access-Control-Request-Headers: *" --header "api-key: $MONGODB_API" --data-raw '{"collection":"relations", "database":"test", "dataSource":"Cluster0"}' > relations.json
echo userrelations downloading...
curl --location --request POST "https://eu-central-1.aws.data.mongodb-api.com/app/data-fnqrm/endpoint/data/v1/action/find" --header "Content-Type: application/json" --header "Access-Control-Request-Headers: *" --header "api-key: $MONGODB_API" --data-raw '{"collection":"userrelations", "database":"test", "dataSource":"Cluster0"}' > userrelations.json
echo users downloading...
curl --location --request POST "https://eu-central-1.aws.data.mongodb-api.com/app/data-fnqrm/endpoint/data/v1/action/find" --header "Content-Type: application/json" --header "Access-Control-Request-Headers: *" --header "api-key: $MONGODB_API" --data-raw '{"collection":"users", "database":"test", "dataSource":"Cluster0"}' > users.json
